ingest: make ingest_jobstats and jobs_with_no_data external-db aware

diff --git a/slurm/ingest_jobstats b/slurm/ingest_jobstats
--- a/slurm/ingest_jobstats
+++ b/slurm/ingest_jobstats
@@ -40,11 +40,20 @@ for i in $(/usr/local/sbin/jobs_with_no_data.py -c $CLUSTER $DAYS $MAXJOBS); do
 	ERR=$?
 	if [ $ERR = 0 ]; then
 		if [[ $STATS =~ ^(Short|None|H4s) ]]; then
-			OUT="`sacctmgr -i update job where jobid=$i set AdminComment=JS1:$STATS 2>&1`"
-			if [ $? != 0 ]; then
-				echo "Job ${i}: Errored out when storing AdminComment with $OUT" >&2
-			elif [ -n $VERBOSE ]; then
-				echo "Job ${i}: Successfully updated job with output ${STATS}"
+			if [ -f "/usr/local/bin/store_jobstats.py" ]; then
+				OUT="`/usr/local/bin/store_jobstats.py --cluster=$CLUSTER --jobid=$i --stats="JS1:$STATS" 2>&1`"
+				if [ $? != 0 ]; then
+					echo "Job ${i}: Errored out when storing external DB jobstats with $OUT" >&2
+				elif [ -n "$VERBOSE" ]; then
+					echo "Job ${i}: Successfully updated external jobstats with output ${STATS}"
+				fi
+			else
+				OUT="`sacctmgr -i update job where jobid=$i set AdminComment=JS1:$STATS 2>&1`"
+				if [ $? != 0 ]; then
+					echo "Job ${i}: Errored out when storing AdminComment with $OUT" >&2
+				elif [ -n "$VERBOSE" ]; then
+					echo "Job ${i}: Successfully updated job with output ${STATS}"
+				fi
 			fi
 		else
 			echo "Job ${i}: Apparent success but invalid output $STATS" >&2
